#!/bin/bash

######
### Create inp files
######

#Generate input files using mplus_inp_template plain text file with MplusAutomation (v1.1.0) createModels function 
R -e 'MplusAutomation::createModels("/scratch/users/k1802739/ALS_LCA/scripts/01_Fitting_LCA/mplus_inp_template")'

######
### Generate bash scripts for each directory 
######

#Specify and create a directory in which all log-files should be returned
logpath=/scratch/users/k1802739/ALS_LCA/logs/
mkdir -p $logpath

#Specify directories generated by the template file
for dir in /scratch/users/k1802739/ALS_LCA/FinalModels/**/
do 
	echo $dir
	
	#Extract model specification to use as job name
	jname=$(basename $dir)
	
	#Minimum runtime for these jobs
	time=35
	
	#Add extra time when running on the joint dataset
	if [[ $dir =~ "JNT" ]]; then
		time=$(expr $time + 5)
	fi
	
	#Create file in script filepath based on template file and move into script directory
	sed -e "s;%dir%;$dir;g" -e "s;%paths%;$jname;g" -e "s;%time%;$time;g" -e "s;%logpath%;$logpath;" /scratch/users/k1802739/ALS_LCA/scripts/01_Fitting_LCA/template_mplusjob.tpl > ${dir}/runMplusJob.sh

done